### ISSUE TITLE
Replace social media icons

### ISSUE THREAD

**Issue by mfb** [EFForg/digitalcitizen#13]
Social media icons: replace w/ below.They turn black on hover.  (Use attached sprite.) 

![social-icons](https://cloud.githubusercontent.com/assets/3278/6879214/29274a30-d4ac-11e4-99d2-d32519f05d97.png)

**Comment by mgerring** [comment]
I kept the existing icons in place but changed the colors. The current icons are better because they're vectors, and therefore resolution independent. If you reeeeeeeally want me to use the sprite I'll do it.
