### ISSUE TITLE
Make sure wordpress caching is fully enabled

### ISSUE THREAD

**Issue by mfb** [EFForg/digitalcitizen#17]
I am not an expert on wordpress but it looks to me like caching is mostly disabled. Would it be a good idea to enable all types of caching for improved scalability of the site?

**Comment by maxateff** [comment]
Hi Matthew,

I made the following changes to DigCit's caching.  Please let me know if anything looks incorrect, or just hop in and update it:

- Enabled page caching using APC
- Enabled minification for HTML, CSS, and JS using the disk.
- Enabled APC caching for MySQL queries
- Added expires, cache-control, and last-modified headers to help with browser caching.

**Comment by mgerring** [comment]
I'll review everything tonight, thanks!

**Comment by mfb** [comment]
we should check the apc cache - it could fill up and get fragmented. the script to check this is apc.php - you have to find it on the server and copy it (temporarily)

**Comment by maxateff** [comment]
Yup, did.  It's in /usr/share/doc/php-apc/apc.php on digcit

**Comment by maxateff** [comment]
(also increased apc memory to 128 mb)
