### ISSUE TITLE
Make sure wordpress plugins and core are up to date

### ISSUE THREAD

**Issue by mfb** [EFForg/digitalcitizen#18]
Could you document how we should go about apply updates to wordpress core and wordpress plugins?

Will it email us when there is an update?

What's the procedure from there?

While you're at it, would be a good thing to ensure all of this stuff is actually up to date :)

**Comment by mgerring** [comment]
You can (and should!!) use the WordPress core updater as normal -- WordPress on the production server is now up to date. Still working on the plugins.

**Comment by mgerring** [comment]
Still working on the plugins. I don't know why WordPress 404s when we dry to auto-update the plugins in production.

**Comment by mfb** [comment]
Fixed a configuration issue on EFF's varnish server, and updating the plugins now works.  Not sure if auto-updating for wordpress core security issues works, but hopefully so!!

**Comment by mgerring** [comment]
Yes, you can run WordPress core updates just fine.

**Comment by mfb** [comment]
to be clear I was wondering if they get automatically applied (which is, I've heard, how wordpress now works) without us having to do anything.
