### ISSUE TITLE
Subhead and navbar design tweaks

### ISSUE THREAD

**Issue by mfb** [EFForg/digitalcitizen#19]
Indent the subhead slightly so that it doesn’t crash into the left margin. See attached png.

Reduce size of nav bar text and align bottom of nav bar text with logo text.

![digicit-b](https://cloud.githubusercontent.com/assets/3278/6892124/ed93e46c-d675-11e4-87b2-4edf59012b25.png)

**Comment by mgerring** [comment]
Fixed with 22e2b61c4559f4e1629b987d12e3e022d3633168
