### ISSUE TITLE
margins

### ISSUE THREAD

**Issue by hughillustration** [EFForg/digitalcitizen#20]
Looking good. Some things need adjusting, others never completed. See PNG for what it should look like:

![digicit-b](https://cloud.githubusercontent.com/assets/10857936/7212971/89817656-e525-11e4-8e2e-566e199403a5.png)

And this copy of the same image has certain items circled in magenta:
![digicit-c](https://cloud.githubusercontent.com/assets/10857936/7212974/b8876168-e525-11e4-8f9f-6b82be0333b0.png)

1. Nav text: Reduce the size of the nav text to 20px.

2. Nav text: move down by 1px

3. Where nav items are active, highlight them as seen in this .png.

4. The language link is crashing into the upper right margin. Indent it by 20px, lower it by 10px.

5. The Volume txt over the image is crashing into the left margin.
Indent it by 20px.

6. Social media icons: replace these with the ones I have used.They turn
black on hover.  (Use attached sprite.)
![social-icons](https://cloud.githubusercontent.com/assets/10857936/7213041/3d2d26a4-e527-11e4-86c8-6d52dcebba56.png)

7. Social media icons: these are crashing into the top margin. Set them
to the same top margin as the initial text (“Digital Citizen is a…”).

8. Initial text (“Digital citizen is a…”): Style as seen in .png.

9. Body text links: style as seen in .png: black with 2px blue
underline. On hover the link should appear as seen in the “here” link at
the top of the page: blue box behind text.

10. Logo cloud: the logos are crashing into each other. Separate them
into two rows, as seen in the .png. Use the attached EFF logo in place
of the one you have used.

**Comment by mgerring** [comment]
Try clearing your cache and refreshing.

**Comment by hughillustration** [comment]
I did clear the cache. Don’t see the changes I requested.

H.

**Comment by mgerring** [comment]
On my machine:

![screenshot from 2015-04-17 18 09 51](https://cloud.githubusercontent.com/assets/287109/7213270/1bfad6ba-e52d-11e4-8d97-fdf9371d2663.png)
![screenshot from 2015-04-17 18 10 04](https://cloud.githubusercontent.com/assets/287109/7213271/1bfbbbc0-e52d-11e4-859f-aa898436d4b8.png)
![screenshot from 2015-04-17 18 10 18](https://cloud.githubusercontent.com/assets/287109/7213269/1bfadd68-e52d-11e4-97b9-1bc34e715c43.png)

**Comment by mfb** [comment]
I believe the difference is cookies. Hugh doesn't have any cookies for the site and is seeing the version cached by Varnish.

I think if you gave Hugh a login to the wordpress site then he would have cookies (or maybe there's another way for him to get a cookie)

**Comment by mfb** [comment]
Ok I figured out how to configure wordpress to cache the CSS for a shorter period of time. So now, if you clear your browser cache you should get the fresh CSS from digcit.org
