### ISSUE TITLE
digcit.org changes: General

### ISSUE THREAD

**Issue by mfb** [EFForg/digitalcitizen#23]
@hughillustration: @mgerring said in https://github.com/EFForg/digitalcitizen/issues/13#issuecomment-90477612 that he needs vector social media icons, can you make vector versions of the png?

@mgerring: more from @hughillustration:

Looking good! Thanks for the fixes made thus far. Some changes to the general layout:

Top nav disappears too quickly. Wait until “volume” hits it?

Nav text: highlight text blue instead of blue bg

Language nav: still crashing into top margin. 10 px plz.

Social icons still wrong, see .PNG

EFF logo: it’s become pixelated. Use the version I sent earlier (attached again here).

EFF logo: It appears some text (reads “EFF”) is overlapping the logo in some views.

![social-icons](https://cloud.githubusercontent.com/assets/3278/7286922/ce795084-e904-11e4-8932-34c6bd2e0194.png)

![eff-logo](https://cloud.githubusercontent.com/assets/3278/7286921/ce77e834-e904-11e4-93b9-c7525cdd43f4.png)

**Comment by hughillustration** [comment]
Yes! But I swapped the chain icon for an email icon, if that’s OK.

H.

**Comment by hughillustration** [comment]
Yes! But I swapped the chain icon for an email icon, if that’s OK.

The blue is wrong, can you be sure to fix to match.

H.

**Comment by mgerring** [comment]
I'm unclear on this issue. Am I replacing any of the icons? And are you using a different blue than the blue used throughout the rest of the site (#00adee)?

**Comment by mfb** [comment]
I'm not sure either. Maybe @hughillustration included some vector files in an e-mail reply but github lost them.  @hughillustration it might be easier if you use the github site and drag/drop the images into the comment text box rather than using email.
