### ISSUE TITLE
support french translation

### ISSUE THREAD

**Issue by mfb** [EFForg/digitalcitizen#34]
We need to tweak the newsletter plugin to support french.

@mgerring anywhere else in the codebase that we might need to add support for french language?

**Comment by mgerring** [comment]
Go here: https://www.digcit.org/wp/wp-admin/tools.php?page=codestyling-localization%2Fcodestyling-localization.php&type=themes. You need to add translations for all of the translation strings in the theme.

**Comment by mgerring** [comment]
We also need to add a menu in French. Polylang takes each menu location defined in the theme and adds a new one for each language. For now, I've set the English primary menu to the French Primary Menu location. Edit the French menu here: https://www.digcit.org/wp/wp-admin/nav-menus.php?action=edit&menu=38

**Comment by mgerring** [comment]
We'll need to make French translations for each of the Pages as well. I went ahead and made the Home page so that when you hit the translation button on the home page you land in the right place.

**Comment by mfb** [comment]
@jilliancyork some translation links being posted in this thread, FYI :)

**Comment by jilliancyork** [comment]
I have the translations done, so I'll go in and try to do that now!

**Comment by jilliancyork** [comment]
Okay, I tried, but I cannot for the life of me figure out how to add the menu items. I can either send them to you to do, or you can explain it to me - sorry about that!

**Comment by mfb** [comment]
I'm not sure either :) @mgerring can you give us some more explanation on this.

**Comment by mgerring** [comment]
Yeah, I sure can.

The first thing you need to do is make French translations for all the
pages.

Then, you go to Appearance > Menus . Select "Primary fr" from the "Select a
menu to edit" dropdown and click "edit". Then, on the left pane, check the
box next to the page you want to ass and click "Add to menu". You'll get a
little Ajax spinner and then the page will be added to the menu. I got you
started by putting the Home Page (Page d’accueil) in the French menu.

Once you get all the pages in there, you can drag, drop and rearrange to
your heart's content.

When you're ready to publish the menu, check the box for "Primary Menu
Français" beneath the list of menu items and click "save menu".

Or, barring all that, just make French translations for the pages and I'll
do the menu stuff for you :)

Let me know if you have any other problems.

Did you figure out the "localization" tool?

--Matthew

**Comment by jilliancyork** [comment]
Hi Matthew,

Sorry, but I can't get these instructions to work. Here's where I'm lost: "click "edit". Then, on the left pane, check the
box next to the page you want to ass and click "Add to menu"."

First, there's no "edit" to click. Second, I don't understand what you mean by "ass" here - is it an abbreviation or a typo? I don't get how the stuff on the left menu corresponds to the original menu items at all.

Also, the French menu seems to be set to English or something?

Yeah, I don't get this one bit, sorry.

What "localization" tool?

-J

**Comment by mfb** [comment]
@mgerring can you confirm that the newsletter will now be sent in french?  The plan is to send it out on Monday.

**Comment by mgerring** [comment]
I'll make the newsletter tweaks before then.

**Comment by maxateff** [comment]
Hi @mgerring -- Kim mentioned that this is almost good to go, except for the translations for the field names.  Those are:

Prènom
Nom
Email
Lien URL
Pays
Envoyer


Prénom
Nom
Email
Envoyer

Let me know if you need anything else!

Max

**Comment by mgerring** [comment]
Can I get them in Arabic too?

**Comment by maxateff** [comment]
Are they not translated in Arabic yet?  Kim and I don't have those.

**Comment by mgerring** [comment]
No, they're not, at the moment they show up in English everywhere.

**Comment by maxateff** [comment]
Got it.  Let's add those for French now; I've submitted a request for the Arabic translations and will send those to you when they come in.

**Comment by mgerring** [comment]
And we're done! I'm opening a separate issue for Arabic.
