### ISSUE TITLE
Featured image thing broken on digcit.org?

### ISSUE THREAD

**Issue by mfb** [EFForg/digitalcitizen#35]
@jilliancyork says she used to only have to set the featured image once and it crossed over to the translations, but today, she had to both upload and set the featured image three times, once per language.

**Comment by mgerring** [comment]
I tested this and couldn't reproduce the error.

I made three test posts. One where I set an existing image as the featured image, one where I uploaded a new featured image by clicking the "set featured image" button and then clicking on "add media", and one where I uploaded the new image first and then set it as the featured image. Doing any of those things, and then making either an Arabic or French translation, correctly copied over the image.

If it happens again, put me in touch with Jillian so I can figure out steps to reproduce.
