### ISSUE TITLE
Digcit.org - featured image function only works sometimes

### ISSUE THREAD

**Issue by maxateff** [EFForg/digitalcitizen#45]
From Jillian:
"When I upload a featured image, it's supposed to (and sometimes does) carry over to the other connected posts (the translations). This sometimes works and sometimes doesn't, so it's possible there's a certain order in which things need to happen but I'm not sure. Can someone please advise?"

**Comment by maxateff** [comment]
@jilliancyork can you add links to a post where this is happening?

**Comment by jilliancyork** [comment]
On 11/3/15 3:33 AM, maxateff wrote:
> @jilliancyork <https://github.com/jilliancyork> can you add links to a
> post where this is happening?

No, because I fix it and upload it separately as it happens. It happened
today with the French edition though - the EN/AR one crossed over just
fine but French did not and I had to upload it separately.

> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/digitalcitizen/issues/45#issuecomment-153220462>.
> 


-- 
*Jillian C. York* Director for International Freedom of Expression
Electronic Frontier Foundation | https://eff.org .de: +493021782883 .us:
+14159407028

**Comment by rocketnova** [comment]
Hi @jilliancyork,

I looked into this issue for you. You are right that there is a certain order in which things need to happen. The following steps will consistently work:

1. Create a new post in EN.
2. Upload the featured image.
2. Save as draft or publish the EN version.
3. In the languages sidebar box, click the + link next to the AR or FR flag to create a new translation post.
4. The new translation post will be associated to the original EN post and the new translation post will have the featured image attached.
5. Repeat step 4 for additional translation posts.

*Note:* The post that you create in step 1 does not need to be in EN. The **important** part of these steps are to always use the + link in the languages sidebar box to create additional language posts and to upload the featured image before you click the + link. If you upload or change the featured image after you click the + link, you will have to re-upload the featured image for each language.

Does that make sense?

Rocket

**Comment by jilliancyork** [comment]
Hey Rocket!

This does make sense BUT...I followed those precise steps last time and
it still went wrong. I'll try again this round and see what happens.

-J



On 11/25/15 2:05 AM, Rocket wrote:
> Hi @jilliancyork <https://github.com/jilliancyork>,
> 
> I looked into this issue for you. You are right that there is a certain
> order in which things need to happen. The following steps will
> consistently work:
> 
>  1. Create a new post in EN.
>  2. Upload the featured image.
>  3. Save as draft or publish the EN version.
>  4. In the languages sidebar box, click the + link next to the AR or FR
>     flag to create a new translation post.
>  5. The new translation post will be associated to the original EN post
>     and the new translation post will have the featured image attached.
>  6. Repeat step 4 for additional translation posts.
> 
> /Note:/ The post that you create in step 1 does not need to be in EN.
> The *important* part of these steps are to always use the + link in the
> languages sidebar box to create additional language posts and to upload
> the featured image before you click the + link. If you upload or change
> the featured image after you click the + link, you will have to
> re-upload the featured image for each language.
> 
> Does that make sense?
> 
> Rocket
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/digitalcitizen/issues/45#issuecomment-159452795>.
> 


-- 
*Jillian C. York* Director for International Freedom of Expression
Electronic Frontier Foundation | https://eff.org .de: +493021782883 .us:
+14159407028

**Comment by rocketnova** [comment]
Hey Jillian,

Hmmm :( Which volume are you referring to? Vol 3.9 or Vol 4.0?

- Rocket

**Comment by jilliancyork** [comment]
I think this is my error - I know I did it correctly for 4.0 so it
should work now, you're right - thanks!

On 11/25/15 6:22 PM, Rocket wrote:
> Hey Jillian,
> 
> Hmmm :( Which volume are you referring to? Vol 3.9 or Vol 4.0?
> 
> - Rocket
> 
>> On Nov 25, 2015, at 2:20 AM, jilliancyork <notifications@github.com>
> wrote:
>>
>> Hey Rocket!
>>
>> This does make sense BUT...I followed those precise steps last time and
>> it still went wrong. I'll try again this round and see what happens.
>>
>> -J
>>
>>
>>
>> On 11/25/15 2:05 AM, Rocket wrote:
>> > Hi @jilliancyork <https://github.com/jilliancyork>,
>> >
>> > I looked into this issue for you. You are right that there is a certain
>> > order in which things need to happen. The following steps will
>> > consistently work:
>> >
>> > 1. Create a new post in EN.
>> > 2. Upload the featured image.
>> > 3. Save as draft or publish the EN version.
>> > 4. In the languages sidebar box, click the + link next to the AR or FR
>> > flag to create a new translation post.
>> > 5. The new translation post will be associated to the original EN post
>> > and the new translation post will have the featured image attached.
>> > 6. Repeat step 4 for additional translation posts.
>> >
>> > /Note:/ The post that you create in step 1 does not need to be in EN.
>> > The *important* part of these steps are to always use the + link in the
>> > languages sidebar box to create additional language posts and to upload
>> > the featured image before you click the + link. If you upload or change
>> > the featured image after you click the + link, you will have to
>> > re-upload the featured image for each language.
>> >
>> > Does that make sense?
>> >
>> > Rocket
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> >
> <https://github.com/EFForg/digitalcitizen/issues/45#issuecomment-159452795>.
>> >
>>
>>
>> --
>> *Jillian C. York* Director for International Freedom of Expression
>> Electronic Frontier Foundation | https://eff.org .de: +493021782883 .us:
>> +14159407028
>>
>> —
>> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/digitalcitizen/issues/45#issuecomment-159562981>.
>>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/digitalcitizen/issues/45#issuecomment-159679485>.
> 


-- 
*Jillian C. York* Director for International Freedom of Expression
Electronic Frontier Foundation | https://eff.org .de: +493021782883 .us:
+14159407028

**Comment by rocketnova** [comment]
That would make sense. Vol 4.0 looks like all the 3 language posts are correctly associated with each other, but Vol 3.9 looks like the FR version is not associated correctly, which would mean that the featured image wouldn’t have carried through.
