### ISSUE TITLE
Translation plugin isn't working, front page is broken

### ISSUE THREAD

**Issue by mgerring** [EFForg/digitalcitizen#48]
Someone or something disabled the translation plugin and the entire site is broken. This should be a relatively easy fix but I don't have credentials to the site anymore and I haven't been able to contact anyone to fix it.

**Comment by mfb** [comment]
I didn't disable it.. but I did try to enable automatic updates of wordpress plugins so I wonder if something related to that broke it.

I reenabled the plugin.

**Comment by mfb** [comment]
@mgerring does everything seem to be ok now?

**Comment by mgerring** [comment]
yep, all good
